//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace login
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exam()
        {
            this.Std_Exam_Ques = new HashSet<Std_Exam_Ques>();
        }
    
        public int Exam_ID { get; set; }
        public Nullable<int> Exam_Grade { get; set; }
        public Nullable<System.DateTime> Exam_Date { get; set; }
        public Nullable<int> Crs_ID { get; set; }
        public Nullable<int> Ins_ID { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Instructor Instructor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Std_Exam_Ques> Std_Exam_Ques { get; set; }
    }
}
