//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace login
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Std_Course = new HashSet<Std_Course>();
            this.Std_Exam_Ques = new HashSet<Std_Exam_Ques>();
        }
    
        public int Std_ID { get; set; }
        public string Std_Fname { get; set; }
        public string Std_Lname { get; set; }
        public System.DateTime Std_BOD { get; set; }
        public string Std_Address { get; set; }
        public string U_UserName { get; set; }
        public Nullable<int> Dept_ID { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Std_Course> Std_Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Std_Exam_Ques> Std_Exam_Ques { get; set; }
        public virtual User User { get; set; }
    }
}
